### ISSUE TITLE
Suggestion: Remove mod name from inner categories

### ISSUE THREAD

**Issue by jpiolho** [BigMo/KCMods#3]
The mod name / version and author is already in the top category so I don't feel there's a need to repeat it in the inner categories.

Here's how it would look:
![image](https://user-images.githubusercontent.com/783467/80111162-d212a700-857f-11ea-95fa-7bf5bbbd6b03.png)

**Comment by BigMo** [comment]
Implemented in d02b40694cf19d3721bce2b4413640e4f3a40e96
